-- ¡ATENCIÓN! Este archivo de esquema estructurado de forma única está DEPRECADO.
-- La fuente de verdad para la base de datos se encuentra ahora en:
--   - Migraciones oficiales: db/migrations/
--   - Semillas oficiales: db/seeds/
--
-- Por favor, utilizá los comandos de npm habilitados en package.json:
--   - npm run db:status  -> Muestra el estado de las migraciones.
--   - npm run db:migrate -> Aplica las migraciones SQL pendientes.
--   - npm run db:seed    -> Ejecuta los datos semilla del catálogo.
